version: '3.8'

services:
  manager:
    build: .
    container_name: go-docker-manager
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Ahora es relativo: busca la carpeta 'stacks' al lado de este archivo
      - ./stacks:/stacks 
      - ./config:/app/config 
    env_file:
      - .env
    user: root