name: Go Docker Manager CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Go
      uses: actions/setup-go@v4
      with:
        # Usamos la versión 1.22 o superior para coincidir con tu go.mod
        go-version: '1.22'

    - name: Instalar dependencias
      run: go mod tidy

    - name: Ejecutar Pruebas
      # Ejecuta todas las pruebas del proyecto. 
      # Gracias a t.Skipf, las pruebas que requieren Docker no romperán el CI.
      run: go test -v ./...
